trigger:
- master
- feature/*

jobs:
- job: rust_static
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 5

  steps:
  - template: ci/rust-static.yml

- job: padre_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 20

  steps:
  - template: ci/padre-tests.yml

- job: vim_tests
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 10

  steps:
  - template: ci/vim-tests.yml
