#!/usr/bin/env node

'use strict'

const net = require('net')

const yargs = require('yargs')

const Debugger = require('./src/debugger/debugger').Debugger
const LLDB = require('./src/debugger/lldb/lldb').LLDB
const NodeInspect = require('./src/debugger/nodeinspect/nodeinspect').NodeInspect

const argv = yargs.options({
  'p': {
    'alias': 'port',
    'describe': 'specify port to run on',
    'default': 12345,
    'type': 'number'
  },
  'host': {
    'describe': 'specify host to run on',
    'default': 'localhost',
    'type': 'string'
  },
  'd': {
    'alias': 'debugger',
    'describe': 'specify debugger to use',
    'default': 'lldb',
    'choices': ['lldb', 'node'],
    'type': 'string'
  }
}).usage(`Usage: $0 [options] -- progname [args]

A tool for building, debugging and reverse engineering in VIM

Interfaces with 'lldb' and 'make' to compile and debug programs written
in C or related languages and can communicate with the vim-padre VIM plugin
in order to effectively use VIM as a debugging interface.`).help('h').alias('h', 'help').argv

if (argv._.length === 0) {
  console.log('Error: No program specified to run')
  process.exit(1)
}

const getDebugServer = (type) => {
  let DebugServerClass
  let options = {}

  switch (type) {
  case 'lldb':
    DebugServerClass = LLDB
    break
  case 'node':
    DebugServerClass = NodeInspect
    break
  }

  const debugServer = new DebugServerClass(argv._[0], argv._.slice(1), options)

  return debugServer
}

const server = net.createServer(async (connection) => {
  const debugServer = getDebugServer(argv.debugger)
  const mainDebugger = new Debugger(debugServer, connection)
  await mainDebugger.setup()
})

server.listen(argv.port, argv.host, () => {
  console.log(`Listening on ${argv.host}:${argv.port}`)
})
